baseURL = "https://enlixe-web.onrender.com/"
title = "Enlixe Web"
paginate = 8
theme = "hugo-PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true

# buildDrafts = false
# buildFuture = false
# buildExpired = false

# googleAnalytics = "UA-123-45"

[minify]
disableXML = true
minifyOutput = true


[languages.en]
languageName = "Home"
weight = 1

  [[languages.en.menu.main]]
  name = "Archives"
  url = "/archives/"
  weight = 5

  [[languages.en.menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 10

  [[languages.en.menu.main]]
  name = "Post"
  url = "/posts/"
  weight = 15

  [[languages.en.menu.main]]
  name = "Patch"
  url = "/patch/"
  weight = 20

[languages.bot]
languageName = "bot"
weight = 2
title = "Enlixe Web"

  [languages.bot.profileMode]
  enabled = true
  title = "Hype Bot"
  subtitle = "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"

    [[languages.bot.profileMode.buttons]]
    name = "Patch"
    url = "/patch/bot"


[params]
env = "production"
title = "Enlixe Web"
description = "Web maked by enlixe"
author = "Enlixe"
images = "<link or path of image for opengraph, twitter-cards>"
ShowReadingTime = true
ShowShareButtons = true
comments = false
defaultTheme = "auto"
disableThemeToggle = false
disableSpecial1stPost = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"


  [params.profileMode]
  enabled = false
  title = "Enlixe"
  imageUrl = "#"
  imageTitle = "Images"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"


  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Welcome to my blog"


  # social icons
  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/EnlixeId/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/Enlixe/"



[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# [params.analytics.google]
# SiteVerificationTag = "XYZabc"